---
abstract: 'Pretty-print data structure as JSON'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires:
  Module::Build: 0.3601
  Test::More: 0.96
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300006, CPAN::Meta::Converter version 2.113640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-Format-Pretty-JSON
requires:
  JSON: 0
  perl: 5.010000
resources:
  homepage: http://search.cpan.org/dist/Data-Format-Pretty-JSON/
  repository: http://github.com/sharyanto/perl-Data-Format-Pretty-JSON
version: 0.04
